"""Add hierarchical subnets and tags

Revision ID: d15db0cc2ce2
Revises: 042dc38cea09
Create Date: 2026-04-28 11:53:49.739722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd15db0cc2ce2'
down_revision: Union[str, Sequence[str], None] = '042dc38cea09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ip_addresses', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_ip_addresses_address'), ['address'])

    with op.batch_alter_table('subnets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_subnets_parent_id'), ['parent_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_subnets_cidr'), ['cidr'])
        batch_op.create_foreign_key(batch_op.f('fk_subnets_parent_id_subnets'), 'subnets', ['parent_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subnets', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_subnets_parent_id_subnets'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_subnets_cidr'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_subnets_parent_id'))
        batch_op.drop_column('tags')
        batch_op.drop_column('parent_id')

    with op.batch_alter_table('ip_addresses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_ip_addresses_address'), type_='unique')

    # ### end Alembic commands ###
